server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

banking:
  services:
    customer-url: http://localhost:8081
    account-url: http://localhost:8082
    credit-url: http://localhost:8083
    wallet-url: http://localhost:8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 2s

security:
  jwt:
    secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
