server:
  port: 8082

spring:
  application:
    name: account-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/accountdb
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      group-id: account-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

banking:
  accounts:
    savings-monthly-movement-limit: 20
    checking-maintenance-fee: 15.00
    minimum-opening-amount: 0.00
    free-transaction-limit: 20
    transaction-fee: 3.50
    vip-monthly-minimum-average-amount: 500.00
    outbox:
      fixed-delay-ms: 5000
      retry-delay-seconds: 10
      max-retries: 3

  kafka:
    retry:
      max-attempts: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      creditService:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
  timelimiter:
    instances:
      creditService:
        timeout-duration: 2s

security:
  jwt:
    secret: ${JWT_SECRET}
